/* BEC 中级词库 — 8 个商务主题, 160 个单词 */
const TOPICS = [
  '商务会议', '商务邮件', '市场营销', '金融财务',
  '人力资源', '国际贸易', '项目管理', '商务战略'
];

const WORDS = [
  // ===== 商务会议 (1-20) =====
  { id: 1, word: 'agenda', phonetic: '/əˈdʒendə/', meaning: '议程', example: 'Please send the agenda before the meeting.', exampleCn: '请在会议前发送议程。', topic: '商务会议' },
  { id: 2, word: 'minutes', phonetic: '/ˈmɪnɪts/', meaning: '会议记录', example: 'Who will take the minutes today?', exampleCn: '今天谁做会议记录？', topic: '商务会议' },
  { id: 3, word: 'proposal', phonetic: '/prəˈpoʊzl/', meaning: '提案，建议书', example: 'We need to prepare a detailed proposal for the client.', exampleCn: '我们需要为客户准备一份详细的提案。', topic: '商务会议' },
  { id: 4, word: 'consensus', phonetic: '/kənˈsensəs/', meaning: '共识，一致意见', example: 'The team reached a consensus on the new strategy.', exampleCn: '团队就新战略达成了一致意见。', topic: '商务会议' },
  { id: 5, word: 'presentation', phonetic: '/ˌpriːzenˈteɪʃn/', meaning: '演示，报告', example: 'She gave an excellent presentation on market trends.', exampleCn: '她就市场趋势做了精彩的演示。', topic: '商务会议' },
  { id: 6, word: 'deadline', phonetic: '/ˈdedlaɪn/', meaning: '截止日期', example: 'We have a tight deadline to meet this week.', exampleCn: '本周我们有一个紧迫的截止日期要赶。', topic: '商务会议' },
  { id: 7, word: 'brainstorm', phonetic: '/ˈbreɪnstɔːrm/', meaning: '头脑风暴', example: 'Let\'s brainstorm some ideas for the campaign.', exampleCn: '让我们为这个活动 brainstorm 一些想法。', topic: '商务会议' },
  { id: 8, word: 'chairperson', phonetic: '/ˈtʃerpɜːrsn/', meaning: '主持人，主席', example: 'The chairperson called the meeting to order.', exampleCn: '主持人宣布会议开始。', topic: '商务会议' },
  { id: 9, word: 'handout', phonetic: '/ˈhændaʊt/', meaning: '讲义，分发材料', example: 'Please collect the handouts at the door.', exampleCn: '请在门口领取分发材料。', topic: '商务会议' },
  { id: 10, word: 'adjourn', phonetic: '/əˈdʒɜːrn/', meaning: '休会， adjourn', example: 'The meeting adjourned at 5 p.m.', exampleCn: '会议在下午5点休会。', topic: '商务会议' },
  { id: 11, word: 'vote', phonetic: '/voʊt/', meaning: '投票', example: 'Let\'s take a vote on the proposal.', exampleCn: '让我们对这个提案进行投票。', topic: '商务会议' },
  { id: 12, word: 'conference', phonetic: '/ˈkɑːnfərəns/', meaning: '会议，研讨会', example: 'We attended a conference on international trade.', exampleCn: '我们参加了一个国际贸易会议。', topic: '商务会议' },
  { id: 13, word: 'resolution', phonetic: '/ˌrezəˈluːʃn/', meaning: '决议', example: 'The board passed a resolution to expand operations.', exampleCn: '董事会通过了扩大业务的决议。', topic: '商务会议' },
  { id: 14, word: 'panel', phonetic: '/ˈpænl/', meaning: '专题讨论小组', example: 'The panel discussed the future of e-commerce.', exampleCn: '专题小组讨论了电子商务的未来。', topic: '商务会议' },
  { id: 15, word: 'summary', phonetic: '/ˈsʌməri/', meaning: '总结，概要', example: 'Can you give a summary of the key points?', exampleCn: '你能总结一下要点吗？', topic: '商务会议' },
  { id: 16, word: 'motion', phonetic: '/ˈmoʊʃn/', meaning: '动议', example: 'The motion was seconded by Mr. Smith.', exampleCn: '该动议得到了史密斯先生的附议。', topic: '商务会议' },
  { id: 17, word: 'attendee', phonetic: '/əˌtenˈdiː/', meaning: '出席者', example: 'All attendees received a welcome package.', exampleCn: '所有出席者都收到了欢迎礼包。', topic: '商务会议' },
  { id: 18, word: 'venue', phonetic: '/ˈvenjuː/', meaning: '会场，地点', example: 'The conference venue can hold 500 people.', exampleCn: '会议场地可容纳500人。', topic: '商务会议' },
  { id: 19, word: 'feedback', phonetic: '/ˈfiːdbæk/', meaning: '反馈', example: 'We received positive feedback from the participants.', exampleCn: '我们收到了参与者的积极反馈。', topic: '商务会议' },
  { id: 20, word: 'networking', phonetic: '/ˈnetwɜːrkɪŋ/', meaning: '社交，建立人脉', example: 'The networking session was very productive.', exampleCn: '社交环节非常有成效。', topic: '商务会议' },

  // ===== 商务邮件 (21-40) =====
  { id: 21, word: 'correspondence', phonetic: '/ˌkɔːrəˈspɑːndəns/', meaning: '通信，函件', example: 'All correspondence should be sent to head office.', exampleCn: '所有函件应发送至总部。', topic: '商务邮件' },
  { id: 22, word: 'attachment', phonetic: '/əˈtætʃmənt/', meaning: '附件', example: 'Please find the report attached.', exampleCn: '请查收附件中的报告。', topic: '商务邮件' },
  { id: 23, word: 'enquiry', phonetic: '/ˈɪnkwəri/', meaning: '询盘，询问', example: 'We received an enquiry about our products.', exampleCn: '我们收到了关于产品的询盘。', topic: '商务邮件' },
  { id: 24, word: 'quote', phonetic: '/kwoʊt/', meaning: '报价', example: 'Please send us a quote for 500 units.', exampleCn: '请给我们报500件的价格。', topic: '商务邮件' },
  { id: 25, word: 'confirm', phonetic: '/kənˈfɜːrm/', meaning: '确认', example: 'Could you confirm your attendance by Friday?', exampleCn: '你能在周五前确认是否参加吗？', topic: '商务邮件' },
  { id: 26, word: 'regarding', phonetic: '/rɪˈɡɑːrdɪŋ/', meaning: '关于', example: 'I am writing regarding your application.', exampleCn: '我写信是关于你的申请。', topic: '商务邮件' },
  { id: 27, word: 'recipient', phonetic: '/rɪˈsɪpiənt/', meaning: '收件人', example: 'All recipients replied within 24 hours.', exampleCn: '所有收件人在24小时内回复了。', topic: '商务邮件' },
  { id: 28, word: 'cc (carbon copy)', phonetic: '/ˈkɑːrbən ˈkɑːpi/', meaning: '抄送', example: 'Please cc the manager on all project emails.', exampleCn: '请在所有项目邮件中抄送经理。', topic: '商务邮件' },
  { id: 29, word: 'subject line', phonetic: '/ˈsʌbdʒɪkt laɪn/', meaning: '主题行', example: 'Use a clear subject line for your email.', exampleCn: '请使用清晰的主题行。', topic: '商务邮件' },
  { id: 30, word: 'follow up', phonetic: '/ˈfɑːloʊ ʌp/', meaning: '跟进', example: 'I will follow up with you next week.', exampleCn: '我下周会跟进你。', topic: '商务邮件' },
  { id: 31, word: 'acknowledge', phonetic: '/əkˈnɑːlɪdʒ/', meaning: '确认收到', example: 'Please acknowledge receipt of this email.', exampleCn: '请确认收到此邮件。', topic: '商务邮件' },
  { id: 32, word: 'forward', phonetic: '/ˈfɔːrwərd/', meaning: '转发', example: 'Please forward the email to your team.', exampleCn: '请将邮件转发给你的团队。', topic: '商务邮件' },
  { id: 33, word: 'reply', phonetic: '/rɪˈplaɪ/', meaning: '回复', example: 'I look forward to your reply.', exampleCn: '期待你的回复。', topic: '商务邮件' },
  { id: 34, word: 'draft', phonetic: '/dræft/', meaning: '草稿', example: 'I\'ll draft a proposal and send it for review.', exampleCn: '我会起草一份提案并发送审阅。', topic: '商务邮件' },
  { id: 35, word: 'inquiry', phonetic: '/ˈɪnkwəri/', meaning: '询问，查询', example: 'Thank you for your inquiry about our services.', exampleCn: '感谢您对我们的服务进行询价。', topic: '商务邮件' },
  { id: 36, word: 'correspond', phonetic: '/ˌkɔːrəˈspɑːnd/', meaning: '通信', example: 'We have corresponded for several months.', exampleCn: '我们已经通信几个月了。', topic: '商务邮件' },
  { id: 37, word: 'notification', phonetic: '/ˌnoʊtɪfɪˈkeɪʃn/', meaning: '通知', example: 'You will receive a notification when the order ships.', exampleCn: '订单发货时你会收到通知。', topic: '商务邮件' },
  { id: 38, word: 'memo', phonetic: '/ˈmemoʊ/', meaning: '备忘录', example: 'The CEO sent a memo to all employees.', exampleCn: 'CEO 给所有员工发了备忘录。', topic: '商务邮件' },
  { id: 39, word: 'abbreviation', phonetic: '/əˌbriːviˈeɪʃn/', meaning: '缩写', example: 'ASAP is a common abbreviation in business emails.', exampleCn: 'ASAP 是商务邮件中常见的缩写。', topic: '商务邮件' },
  { id: 40, word: 'address', phonetic: '/əˈdres/', meaning: '处理，解决', example: 'We need to address these issues immediately.', exampleCn: '我们需要立即处理这些问题。', topic: '商务邮件' },

  // ===== 市场营销 (41-60) =====
  { id: 41, word: 'brand', phonetic: '/brænd/', meaning: '品牌', example: 'Our brand is known for quality and reliability.', exampleCn: '我们的品牌以质量和可靠性著称。', topic: '市场营销' },
  { id: 42, word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: '活动，营销活动', example: 'The advertising campaign boosted sales by 20%.', exampleCn: '广告活动使销售额增长了20%。', topic: '市场营销' },
  { id: 43, word: 'target audience', phonetic: '/ˈtɑːrɡɪt ˈɔːdiəns/', meaning: '目标受众', example: 'The campaign is aimed at a young target audience.', exampleCn: '这个活动针对的是年轻的目标受众。', topic: '市场营销' },
  { id: 44, word: 'market share', phonetic: '/ˈmɑːrkɪt ʃer/', meaning: '市场份额', example: 'Our market share has increased by 5% this year.', exampleCn: '我们的市场份额今年增长了5%。', topic: '市场营销' },
  { id: 45, word: 'promotion', phonetic: '/prəˈmoʊʃn/', meaning: '促销，推广', example: 'The promotion offers 20% off all products.', exampleCn: '促销活动对所有产品打八折。', topic: '市场营销' },
  { id: 46, word: 'consumer', phonetic: '/kənˈsuːmər/', meaning: '消费者', example: 'Consumer demand for eco-friendly products is growing.', exampleCn: '消费者对环保产品的需求正在增长。', topic: '市场营销' },
  { id: 47, word: 'launch', phonetic: '/lɔːntʃ/', meaning: '推出，发布', example: 'The company will launch its new product next month.', exampleCn: '公司将在下个月推出新产品。', topic: '市场营销' },
  { id: 48, word: 'advertise', phonetic: '/ˈædvərtaɪz/', meaning: '做广告', example: 'We advertise on social media platforms.', exampleCn: '我们在社交媒体平台上做广告。', topic: '市场营销' },
  { id: 49, word: 'logo', phonetic: '/ˈloʊɡoʊ/', meaning: '标识，商标', example: 'The new logo represents our company values.', exampleCn: '新标志代表了公司的价值观。', topic: '市场营销' },
  { id: 50, word: 'retail', phonetic: '/ˈriːteɪl/', meaning: '零售', example: 'The retail price is $49.99.', exampleCn: '零售价为49.99美元。', topic: '市场营销' },
  { id: 51, word: 'wholesale', phonetic: '/ˈhoʊlseɪl/', meaning: '批发', example: 'Wholesale prices are 30% lower than retail.', exampleCn: '批发价比零售价低30%。', topic: '市场营销' },
  { id: 52, word: 'survey', phonetic: '/ˈsɜːrveɪ/', meaning: '调查', example: 'A customer satisfaction survey was conducted.', exampleCn: '进行了一项客户满意度调查。', topic: '市场营销' },
  { id: 53, word: 'competitive', phonetic: '/kəmˈpetətɪv/', meaning: '有竞争力的', example: 'We offer competitive prices and high quality.', exampleCn: '我们提供有竞争力的价格和高质量。', topic: '市场营销' },
  { id: 54, word: 'endorse', phonetic: '/ɪnˈdɔːrs/', meaning: '代言，背书', example: 'A famous athlete endorsed our product.', exampleCn: '一位著名运动员代言了我们的产品。', topic: '市场营销' },
  { id: 55, word: 'segment', phonetic: '/ˈseɡmənt/', meaning: '细分市场', example: 'We target the premium market segment.', exampleCn: '我们针对的是高端细分市场。', topic: '市场营销' },
  { id: 56, word: 'catalogue', phonetic: '/ˈkætəlɔːɡ/', meaning: '产品目录', example: 'Our catalogue features over 500 products.', exampleCn: '我们的产品目录收录了500多种产品。', topic: '市场营销' },
  { id: 57, word: 'franchise', phonetic: '/ˈfræntʃaɪz/', meaning: '特许经营', example: 'They opened a franchise in Shanghai.', exampleCn: '他们在上海开了一家特许经营店。', topic: '市场营销' },
  { id: 58, word: 'positioning', phonetic: '/pəˈzɪʃənɪŋ/', meaning: '定位', example: 'Brand positioning is crucial for market success.', exampleCn: '品牌定位对市场成功至关重要。', topic: '市场营销' },
  { id: 59, word: 'slogan', phonetic: '/ˈsloʊɡən/', meaning: '标语，口号', example: 'The company\'s slogan is "Quality First".', exampleCn: '公司的口号是"质量第一"。', topic: '市场营销' },
  { id: 60, word: 'distribution', phonetic: '/ˌdɪstrɪˈbjuːʃn/', meaning: '分销，配送', example: 'Our distribution network covers all major cities.', exampleCn: '我们的分销网络覆盖所有主要城市。', topic: '市场营销' },

  // ===== 金融财务 (61-80) =====
  { id: 61, word: 'revenue', phonetic: '/ˈrevənuː/', meaning: '收入，营收', example: 'Annual revenue reached $10 million.', exampleCn: '年收入达到1000万美元。', topic: '金融财务' },
  { id: 62, word: 'budget', phonetic: '/ˈbʌdʒɪt/', meaning: '预算', example: 'The project is within budget.', exampleCn: '项目在预算范围内。', topic: '金融财务' },
  { id: 63, word: 'invoice', phonetic: '/ˈɪnvɔɪs/', meaning: '发票', example: 'Please send the invoice by email.', exampleCn: '请通过邮件发送发票。', topic: '金融财务' },
  { id: 64, word: 'profit', phonetic: '/ˈprɑːfɪt/', meaning: '利润', example: 'Net profit increased by 15% this quarter.', exampleCn: '本季度净利润增长了15%。', topic: '金融财务' },
  { id: 65, word: 'expense', phonetic: '/ɪkˈspens/', meaning: '费用，开支', example: 'We need to cut operating expenses.', exampleCn: '我们需要削减运营开支。', topic: '金融财务' },
  { id: 66, word: 'asset', phonetic: '/ˈæset/', meaning: '资产', example: 'The company\'s total assets are valued at $5 million.', exampleCn: '公司总资产价值500万美元。', topic: '金融财务' },
  { id: 67, word: 'liability', phonetic: '/ˌlaɪəˈbɪləti/', meaning: '负债', example: 'The company has liabilities of $2 million.', exampleCn: '公司有200万美元的负债。', topic: '金融财务' },
  { id: 68, word: 'audit', phonetic: '/ˈɔːdɪt/', meaning: '审计', example: 'An external audit is conducted annually.', exampleCn: '每年进行一次外部审计。', topic: '金融财务' },
  { id: 69, word: 'depreciation', phonetic: '/dɪˌpriːʃiˈeɪʃn/', meaning: '折旧', example: 'The depreciation of equipment is calculated monthly.', exampleCn: '设备折旧按月计算。', topic: '金融财务' },
  { id: 70, word: 'equity', phonetic: '/ˈekwəti/', meaning: '股权，净资产', example: 'They raised equity capital from investors.', exampleCn: '他们从投资者那里筹集了股权资本。', topic: '金融财务' },
  { id: 71, word: 'dividend', phonetic: '/ˈdɪvɪdend/', meaning: '股息，分红', example: 'The company pays a dividend twice a year.', exampleCn: '公司每年支付两次股息。', topic: '金融财务' },
  { id: 72, word: 'interest rate', phonetic: '/ˈɪntrəst reɪt/', meaning: '利率', example: 'The interest rate on the loan is 5%.', exampleCn: '贷款利率为5%。', topic: '金融财务' },
  { id: 73, word: 'cash flow', phonetic: '/kæʃ floʊ/', meaning: '现金流', example: 'Positive cash flow is essential for business survival.', exampleCn: '正向现金流对企业生存至关重要。', topic: '金融财务' },
  { id: 74, word: 'overdraft', phonetic: '/ˈoʊvərdræft/', meaning: '透支', example: 'The bank approved an overdraft facility.', exampleCn: '银行批准了透支额度。', topic: '金融财务' },
  { id: 75, word: 'insolvent', phonetic: '/ɪnˈsɑːlvənt/', meaning: '破产的，无力偿债的', example: 'The company became insolvent and ceased trading.', exampleCn: '公司破产并停止交易。', topic: '金融财务' },
  { id: 76, word: 'credit', phonetic: '/ˈkredɪt/', meaning: '信贷，赊账', example: 'We offer credit terms of 30 days.', exampleCn: '我们提供30天的信用期。', topic: '金融财务' },
  { id: 77, word: 'bankruptcy', phonetic: '/ˈbæŋkrʌptsi/', meaning: '破产', example: 'The company filed for bankruptcy protection.', exampleCn: '公司申请了破产保护。', topic: '金融财务' },
  { id: 78, word: 'ledger', phonetic: '/ˈledʒər/', meaning: '分类账', example: 'The accountant updated the general ledger.', exampleCn: '会计更新了总分类账。', topic: '金融财务' },
  { id: 79, word: 'mortgage', phonetic: '/ˈmɔːrɡɪdʒ/', meaning: '抵押贷款', example: 'They took out a mortgage to buy the office building.', exampleCn: '他们办理了抵押贷款购买写字楼。', topic: '金融财务' },
  { id: 80, word: 'shareholder', phonetic: '/ˈʃerhoʊldər/', meaning: '股东', example: 'The shareholders voted on the merger proposal.', exampleCn: '股东对合并提案进行了投票。', topic: '金融财务' },

  // ===== 人力资源 (81-100) =====
  { id: 81, word: 'recruit', phonetic: '/rɪˈkruːt/', meaning: '招聘', example: 'The company is recruiting new sales staff.', exampleCn: '公司正在招聘新的销售人员。', topic: '人力资源' },
  { id: 82, word: 'interview', phonetic: '/ˈɪntərvjuː/', meaning: '面试', example: 'She has an interview for the manager position.', exampleCn: '她有一个经理职位的面试。', topic: '人力资源' },
  { id: 83, word: 'resume', phonetic: '/ˈrezəmeɪ/', meaning: '简历', example: 'Please attach your resume and cover letter.', exampleCn: '请附上你的简历和求职信。', topic: '人力资源' },
  { id: 84, word: 'salary', phonetic: '/ˈsæləri/', meaning: '薪资', example: 'The salary package includes bonuses and benefits.', exampleCn: '薪资方案包括奖金和福利。', topic: '人力资源' },
  { id: 85, word: 'promotion', phonetic: '/prəˈmoʊʃn/', meaning: '升职', example: 'She got a promotion after three years with the company.', exampleCn: '她在公司工作三年后获得了升职。', topic: '人力资源' },
  { id: 86, word: 'resignation', phonetic: '/ˌrezɪɡˈneɪʃn/', meaning: '辞职', example: 'He handed in his resignation yesterday.', exampleCn: '他昨天递交了辞职信。', topic: '人力资源' },
  { id: 87, word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: '福利', example: 'The benefits include health insurance and pension.', exampleCn: '福利包括健康保险和养老金。', topic: '人力资源' },
  { id: 88, word: 'probation', phonetic: '/proʊˈbeɪʃn/', meaning: '试用期', example: 'New employees have a three-month probation period.', exampleCn: '新员工有三个月的试用期。', topic: '人力资源' },
  { id: 89, word: 'appraisal', phonetic: '/əˈpreɪzl/', meaning: '绩效评估', example: 'Annual appraisals are conducted in December.', exampleCn: '每年十二月进行绩效评估。', topic: '人力资源' },
  { id: 90, word: 'dismiss', phonetic: '/dɪsˈmɪs/', meaning: '解雇', example: 'The employee was dismissed for misconduct.', exampleCn: '该员工因行为不当被解雇。', topic: '人力资源' },
  { id: 91, word: 'overtime', phonetic: '/ˈoʊvərtaɪm/', meaning: '加班', example: 'Staff are paid extra for overtime work.', exampleCn: '员工加班可获得额外报酬。', topic: '人力资源' },
  { id: 92, word: 'bonus', phonetic: '/ˈboʊnəs/', meaning: '奖金', example: 'Everyone received a year-end bonus.', exampleCn: '每个人都获得了年终奖金。', topic: '人力资源' },
  { id: 93, word: 'pension', phonetic: '/ˈpenʃn/', meaning: '养老金', example: 'The company contributes to a pension plan.', exampleCn: '公司向养老金计划缴纳费用。', topic: '人力资源' },
  { id: 94, word: 'staff turnover', phonetic: '/stæf ˈtɜːrnoʊvər/', meaning: '员工流动率', example: 'High staff turnover is a problem in the industry.', exampleCn: '高员工流动率是这个行业的问题。', topic: '人力资源' },
  { id: 95, word: 'headhunt', phonetic: '/ˈhedhʌnt/', meaning: '猎头', example: 'We hired a headhunter to find a new CEO.', exampleCn: '我们请了猎头寻找新的CEO。', topic: '人力资源' },
  { id: 96, word: 'internship', phonetic: '/ˈɪntɜːrnʃɪp/', meaning: '实习', example: 'She completed an internship at a law firm.', exampleCn: '她在一家律师事务所完成了实习。', topic: '人力资源' },
  { id: 97, word: 'notice', phonetic: '/ˈnoʊtɪs/', meaning: '通知期', example: 'The notice period is one month.', exampleCn: '通知期为一个月。', topic: '人力资源' },
  { id: 98, word: 'qualification', phonetic: '/ˌkwɑːlɪfɪˈkeɪʃn/', meaning: '资格，资质', example: 'What qualifications do you have for this job?', exampleCn: '你有哪些资格适合这份工作？', topic: '人力资源' },
  { id: 99, word: 'redundancy', phonetic: '/rɪˈdʌndənsi/', meaning: '裁员', example: 'The factory closure led to 200 redundancies.', exampleCn: '工厂关闭导致200人被裁员。', topic: '人力资源' },
  { id: 100, word: 'training', phonetic: '/ˈtreɪnɪŋ/', meaning: '培训', example: 'All staff receive regular training.', exampleCn: '所有员工都接受定期培训。', topic: '人力资源' },

  // ===== 国际贸易 (101-120) =====
  { id: 101, word: 'export', phonetic: '/ˈekspɔːrt/', meaning: '出口', example: 'The company exports goods to over 30 countries.', exampleCn: '公司向30多个国家出口商品。', topic: '国际贸易' },
  { id: 102, word: 'import', phonetic: '/ˈɪmpɔːrt/', meaning: '进口', example: 'We import raw materials from China.', exampleCn: '我们从中国进口原材料。', topic: '国际贸易' },
  { id: 103, word: 'tariff', phonetic: '/ˈtærɪf/', meaning: '关税', example: 'New tariffs on steel were introduced.', exampleCn: '对钢铁征收了新的关税。', topic: '国际贸易' },
  { id: 104, word: 'quota', phonetic: '/ˈkwoʊtə/', meaning: '配额', example: 'The import quota was reduced this year.', exampleCn: '今年的进口配额减少了。', topic: '国际贸易' },
  { id: 105, word: 'customs', phonetic: '/ˈkʌstəmz/', meaning: '海关', example: 'The goods were cleared through customs.', exampleCn: '货物通过了海关清关。', topic: '国际贸易' },
  { id: 106, word: 'freight', phonetic: '/freɪt/', meaning: '货运，运费', example: 'Freight costs have increased due to fuel prices.', exampleCn: '由于燃料价格上涨，运费增加了。', topic: '国际贸易' },
  { id: 107, word: 'letter of credit', phonetic: '/ˈletər əv ˈkredɪt/', meaning: '信用证', example: 'Payment is by irrevocable letter of credit.', exampleCn: '付款方式为不可撤销信用证。', topic: '国际贸易' },
  { id: 108, word: 'bill of lading', phonetic: '/bɪl əv ˈleɪdɪŋ/', meaning: '提单', example: 'The bill of lading confirms receipt of the goods.', exampleCn: '提单确认货物已收到。', topic: '国际贸易' },
  { id: 109, word: 'duty', phonetic: '/ˈduːti/', meaning: '关税， duty', example: 'Import duty is calculated as a percentage of value.', exampleCn: '进口关税按价值百分比计算。', topic: '国际贸易' },
  { id: 110, word: 'free trade', phonetic: '/friː treɪd/', meaning: '自由贸易', example: 'The two countries signed a free trade agreement.', exampleCn: '两国签署了自由贸易协定。', topic: '国际贸易' },
  { id: 111, word: 'subsidy', phonetic: '/ˈsʌbsədi/', meaning: '补贴', example: 'The government provides export subsidies.', exampleCn: '政府提供出口补贴。', topic: '国际贸易' },
  { id: 112, word: 'embargo', phonetic: '/ɪmˈbɑːrɡoʊ/', meaning: '禁运', example: 'An embargo was placed on certain goods.', exampleCn: '对某些商品实施了禁运。', topic: '国际贸易' },
  { id: 113, word: 'multinational', phonetic: '/ˌmʌltiˈnæʃnəl/', meaning: '跨国公司的', example: 'She works for a multinational corporation.', exampleCn: '她在一家跨国公司工作。', topic: '国际贸易' },
  { id: 114, word: 'outsource', phonetic: '/ˈaʊtsɔːrs/', meaning: '外包', example: 'The company outsources its IT support to India.', exampleCn: '公司把IT支持外包给了印度。', topic: '国际贸易' },
  { id: 115, word: 'supply chain', phonetic: '/səˈplaɪ tʃeɪn/', meaning: '供应链', example: 'The pandemic disrupted global supply chains.', exampleCn: '疫情扰乱了全球供应链。', topic: '国际贸易' },
  { id: 116, word: 'warehouse', phonetic: '/ˈwerhaʊs/', meaning: '仓库', example: 'Goods are stored in the warehouse before shipment.', exampleCn: '货物在装运前存储在仓库中。', topic: '国际贸易' },
  { id: 117, word: 'consignment', phonetic: '/kənˈsaɪnmənt/', meaning: '寄售，托运', example: 'A consignment of goods arrived at the port.', exampleCn: '一批货物已到达港口。', topic: '国际贸易' },
  { id: 118, word: 'inspection', phonetic: '/ɪnˈspekʃn/', meaning: '检验', example: 'The goods passed quality inspection.', exampleCn: '货物通过了质量检验。', topic: '国际贸易' },
  { id: 119, word: 'exchange rate', phonetic: '/ɪksˈtʃeɪndʒ reɪt/', meaning: '汇率', example: 'The exchange rate fluctuates daily.', exampleCn: '汇率每天波动。', topic: '国际贸易' },
  { id: 120, word: 'logistics', phonetic: '/ləˈdʒɪstɪks/', meaning: '物流', example: 'Logistics management is key to international trade.', exampleCn: '物流管理是国际贸易的关键。', topic: '国际贸易' },

  // ===== 项目管理 (121-140) =====
  { id: 121, word: 'milestone', phonetic: '/ˈmaɪlstoʊn/', meaning: '里程碑', example: 'The project reached an important milestone.', exampleCn: '项目达到了一个重要里程碑。', topic: '项目管理' },
  { id: 122, word: 'stakeholder', phonetic: '/ˈsteɪkhoʊldər/', meaning: '利益相关者', example: 'All stakeholders were informed of the progress.', exampleCn: '所有利益相关者都被告知了进展。', topic: '项目管理' },
  { id: 123, word: 'deliverable', phonetic: '/dɪˈlɪvərəbl/', meaning: '可交付成果', example: 'The first deliverable is due next month.', exampleCn: '第一个可交付成果应于下月完成。', topic: '项目管理' },
  { id: 124, word: 'timeline', phonetic: '/ˈtaɪmlaɪn/', meaning: '时间表', example: 'The project timeline was revised.', exampleCn: '项目时间表已修订。', topic: '项目管理' },
  { id: 125, word: 'scope', phonetic: '/skoʊp/', meaning: '范围', example: 'The scope of work includes market research.', exampleCn: '工作范围包括市场调研。', topic: '项目管理' },
  { id: 126, word: 'risk', phonetic: '/rɪsk/', meaning: '风险', example: 'A risk assessment was carried out.', exampleCn: '进行了风险评估。', topic: '项目管理' },
  { id: 127, word: 'contingency', phonetic: '/kənˈtɪndʒənsi/', meaning: '应急方案', example: 'We have a contingency plan in case of delays.', exampleCn: '我们有应对延误的应急方案。', topic: '项目管理' },
  { id: 128, word: 'resource', phonetic: '/ˈriːsɔːrs/', meaning: '资源', example: 'We need to allocate more resources to this project.', exampleCn: '我们需要给这个项目分配更多资源。', topic: '项目管理' },
  { id: 129, word: 'deadline', phonetic: '/ˈdedlaɪn/', meaning: '最后期限', example: 'The deadline for completion is June 30.', exampleCn: '完成的最后期限是6月30日。', topic: '项目管理' },
  { id: 130, word: 'coordinate', phonetic: '/koʊˈɔːrdɪneɪt/', meaning: '协调', example: 'She coordinates the work of several teams.', exampleCn: '她协调几个团队的工作。', topic: '项目管理' },
  { id: 131, word: 'implement', phonetic: '/ˈɪmplɪment/', meaning: '实施，执行', example: 'We will implement the new system next quarter.', exampleCn: '我们将在下季度实施新系统。', topic: '项目管理' },
  { id: 132, word: 'monitor', phonetic: '/ˈmɑːnɪtər/', meaning: '监控', example: 'We monitor progress on a weekly basis.', exampleCn: '我们每周监控进展。', topic: '项目管理' },
  { id: 133, word: 'phase', phonetic: '/feɪz/', meaning: '阶段', example: 'The project is in its final phase.', exampleCn: '项目正处于最后阶段。', topic: '项目管理' },
  { id: 134, word: 'criteria', phonetic: '/kraɪˈtɪriə/', meaning: '标准', example: 'The selection criteria are clearly defined.', exampleCn: '选择标准有明确定义。', topic: '项目管理' },
  { id: 135, word: 'feasibility', phonetic: '/ˌfiːzəˈbɪləti/', meaning: '可行性', example: 'A feasibility study was conducted.', exampleCn: '进行了一项可行性研究。', topic: '项目管理' },
  { id: 136, word: 'priority', phonetic: '/praɪˈɔːrəti/', meaning: '优先级', example: 'Customer satisfaction is our top priority.', exampleCn: '客户满意是我们的首要任务。', topic: '项目管理' },
  { id: 137, word: 'postpone', phonetic: '/poʊˈspoʊn/', meaning: '推迟', example: 'The meeting was postponed until next week.', exampleCn: '会议推迟到了下周。', topic: '项目管理' },
  { id: 138, word: 'oversee', phonetic: '/ˌoʊvərˈsiː/', meaning: '监督， overseeing', example: 'He oversees the entire production process.', exampleCn: '他监督整个生产过程。', topic: '项目管理' },
  { id: 139, word: 'specification', phonetic: '/ˌspesɪfɪˈkeɪʃn/', meaning: '规格，规范', example: 'The technical specifications were approved.', exampleCn: '技术规格已获批准。', topic: '项目管理' },
  { id: 140, word: 'subcontract', phonetic: '/ˌsʌbˈkɑːntrækt/', meaning: '分包', example: 'We subcontract some work to specialized firms.', exampleCn: '我们将一些工作分包给专业公司。', topic: '项目管理' },

  // ===== 商务战略 (141-160) =====
  { id: 141, word: 'merger', phonetic: '/ˈmɜːrdʒər/', meaning: '合并', example: 'The merger created the largest company in the sector.', exampleCn: '这次合并造就了该行业最大的公司。', topic: '商务战略' },
  { id: 142, word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', meaning: '收购', example: 'The acquisition cost $50 million.', exampleCn: '收购花费了5000万美元。', topic: '商务战略' },
  { id: 143, word: 'diversification', phonetic: '/daɪˌvɜːrsɪfɪˈkeɪʃn/', meaning: '多元化', example: 'Diversification reduces business risk.', exampleCn: '多元化降低商业风险。', topic: '商务战略' },
  { id: 144, word: 'competitive advantage', phonetic: '/kəmˈpetətɪv ədˈvæntɪdʒ/', meaning: '竞争优势', example: 'Our technology gives us a competitive advantage.', exampleCn: '我们的技术给了我们竞争优势。', topic: '商务战略' },
  { id: 145, word: 'downsize', phonetic: '/ˈdaʊnsaɪz/', meaning: '精简，裁员', example: 'The company downsized to reduce costs.', exampleCn: '公司通过精简来降低成本。', topic: '商务战略' },
  { id: 146, word: 'outsource', phonetic: '/ˈaʊtsɔːrs/', meaning: '外包', example: 'We outsource manufacturing to Asia.', exampleCn: '我们把制造外包到亚洲。', topic: '商务战略' },
  { id: 147, word: 'joint venture', phonetic: '/dʒɔɪnt ˈventʃər/', meaning: '合资企业', example: 'They formed a joint venture with a local partner.', exampleCn: '他们与当地合作伙伴成立了合资企业。', topic: '商务战略' },
  { id: 148, word: 'takeover', phonetic: '/ˈteɪkoʊvər/', meaning: '接管，收购', example: 'The takeover bid was rejected by the board.', exampleCn: '收购要约被董事会拒绝了。', topic: '商务战略' },
  { id: 149, word: 'franchise', phonetic: '/ˈfræntʃaɪz/', meaning: '特许经营', example: 'The franchise expanded rapidly across the country.', exampleCn: '该特许经营在全国迅速扩张。', topic: '商务战略' },
  { id: 150, word: 'stake', phonetic: '/steɪk/', meaning: '股份，股权', example: 'The company sold a 20% stake to investors.', exampleCn: '公司向投资者出售了20%的股份。', topic: '商务战略' },
  { id: 151, word: 'leverage', phonetic: '/ˈlevərɪdʒ/', meaning: '杠杆作用，利用', example: 'We can leverage our brand to enter new markets.', exampleCn: '我们可以利用品牌进入新市场。', topic: '商务战略' },
  { id: 152, word: 'synergy', phonetic: '/ˈsɪnərdʒi/', meaning: '协同效应', example: 'The merger created significant synergies.', exampleCn: '合并产生了显著的协同效应。', topic: '商务战略' },
  { id: 153, word: 'benchmark', phonetic: '/ˈbentʃmɑːrk/', meaning: '基准，标杆', example: 'We benchmark our performance against industry leaders.', exampleCn: '我们以行业领导者为基准来衡量表现。', topic: '商务战略' },
  { id: 154, word: 'recession', phonetic: '/rɪˈseʃn/', meaning: '经济衰退', example: 'The company survived the recession.', exampleCn: '公司度过了经济衰退。', topic: '商务战略' },
  { id: 155, word: 'portfolio', phonetic: '/pɔːrtˈfoʊlioʊ/', meaning: '业务组合', example: 'Our product portfolio includes both hardware and software.', exampleCn: '我们的产品组合包括硬件和软件。', topic: '商务战略' },
  { id: 156, word: 'spin-off', phonetic: '/ˈspɪn ɔːf/', meaning: '分拆', example: 'The company spun off its software division.', exampleCn: '公司分拆了其软件部门。', topic: '商务战略' },
  { id: 157, word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: '分配', example: 'Resources were allocated to the new project.', exampleCn: '资源被分配给了新项目。', topic: '商务战略' },
  { id: 158, word: 'revenue stream', phonetic: '/ˈrevənuː striːm/', meaning: '收入来源', example: 'Subscription fees are a steady revenue stream.', exampleCn: '订阅费是一个稳定的收入来源。', topic: '商务战略' },
  { id: 159, word: 'restructure', phonetic: '/ˌriːˈstrʌktʃər/', meaning: '重组', example: 'The company restructured its operations.', exampleCn: '公司对其运营进行了重组。', topic: '商务战略' },
  { id: 160, word: 'sustainable', phonetic: '/səˈsteɪnəbl/', meaning: '可持续的', example: 'We aim for sustainable long-term growth.', exampleCn: '我们追求可持续的长期增长。', topic: '商务战略' },
];
